### ISSUE TITLE
Cave biomes not spawning

### ISSUE THREAD

**Issue by StrangerSon713** [TerraForged/tracker#109]
Have both cave and cliff backport and darker depths. Have other generation mods. Cave biome overlays(Quark) still spawning.

**Comment by Won-Ton** [comment]
Neither of these mods are public source so you'd have to ask them to add support. It's most likely they rely on the vanilla implementation of worldgen (which TF is not remotely) which is probably why it doesn't work out the box

**Comment by ItsBlackGear** [comment]
o/ hallo!
the cave biome system is actually not implemented in any of those two mods, but in bgcore (reason why it is a dependency for both of those mods), bgcore (may need a rename soon) is open source and has an API that allows the implementation of cave biomes and the injection of those in modded world types.

even if it's open source, the source code is outdated since we lack of documentation ;w;

**Comment by StrangerSon713** [comment]
@Won-Ton  please talk to blackgear!
