### ISSUE TITLE
Compatibility issues regarding Tinkers Construct structure generation.

### ISSUE THREAD

**Issue by paulhlschr** [TerraForged/tracker#116]
### Description
There seem to be incompatibilities regarding Tinkers Construct slime islands (or structure in general) with TerraForged generation. As seen in the screenshot below, slime islands get generated regularly, ignoring the separation values defined in TC's common configuration. Using TC without TerraForged works without issues, therefore there has to be a compatibility issue between them.

Given TF's AND TC's popularity in the mod space, this incompatibility could result in weighing up between TF and TC. 
According to KnightMiner, ...
> Tinkers does exactly what they [TerraForged] say is needed for compatibility and it does not work

### Reference
For further information please refer to [issue #4473](https://github.com/SlimeKnights/TinkersConstruct/issues/4473) over at TC's repository, too.

### Versions
- TerraForged 1.16.5-0.2.10
- Tinkers Construct 1.16.5-3.0.3.152

### Example screenshot
Using default TerraForged generation settings and **tripled(!)** slime island separation settings

![2021-05-17_17 56 25](https://user-images.githubusercontent.com/20583201/118519252-3da25600-b739-11eb-9dc8-446997cc1ec9.png)

**Comment by relsqui** [comment]
A little more information:

* Changing TF's structure settings for those islands did work, so it seems like it might just be the defaults which aren't getting set properly.
* But I didn't see TF settings for the nether and end slime islands at all, not sure if they're in a different place or missing.
* Unless there's a way to apply updated TF settings to new chunks in an existing world, these islands aren't configurable at all in saved games. This is effectively blocking people using both mods from updating TC (and any other mod that provides structures we want to configure).

**Comment by MercyWhistles** [comment]
Did you find a fix Relsqui? 
How did you change the structure settings? 
I changed the config and it didn't register the update to it. Is there a way to completely disable that structures particular spawning?

**Comment by relsqui** [comment]
On a new world, you can customize the Terraforged world type. There's a section for structures. (TC's config is ignored, as far as I can tell.) I'm not aware of any way to change structure settings for an existing world, which is what I also need.

**Comment by Won-Ton** [comment]
- You can't change structure settings for existing worlds under TF because it breaks things like structure locating in existing chunks.
- As you've pointed out; to configure structures you can use the TF world-gen config screen.
- TC's config doesn't work because they don't actually update the structure settings _data_ when the config changes. They redirect reads of the data to their config, but don't actually update the data value (besides perhaps when the game first loads, so you might be able to edit the config & restart MC with success) - when minecraft converts those settings to/from json, their config redirects are lost and you end up with just the unmodified data values which is what TF sees. TC will have similar issues if you were to configure their structures via datapack and then later want to change the settings via their config. This isn't TF's issue.

**Comment by Won-Ton** [comment]
Oh missed this point:
- TF has nothing to do with nether/end generation besides letting you choose which mod (or vanilla) should handle the generation. TC's config system may or may not work with whatever generator you choose.

**Comment by relsqui** [comment]
Thanks for clarifying! I'll bring that back to the TC thread in case that fix would allow me to save my current world, but unfortunately not being able to update settings in general will probably prevent me from using TF going forward, since it's more important to me to be able to get new updates from other mods in general without having to commit to always using their default settings.

**Comment by MercyWhistles** [comment]
Same here  the terrain generation is definitely a solid 9/10, but I wish there was more effort put into making it somewhat more compatible

**Comment by Won-Ton** [comment]
TF is designed from the ground up for compatibility. We use and adhere to the datapack and world-gen systems defined in vanilla so that when other mods are written (correctly) for those systems they work with ours too. If mods are operating outside the normal parameters of said systems it's on them to make sure they actually work.

If you want to be able to change structure configurations after world creation you could try configure the structure settings via datapack and update that as required. We don't offer that via our UI as we consider that breaking a breaking change to your world.

By all means drop TF if that's too much hassle for you, just know that we do infact go to great lengths to work with as many mods as possible.
