### ISSUE TITLE
Permanent waiting for server state

### ISSUE THREAD

**Issue by NillerMedDild** [TerraForged/tracker#125]
Original issue: https://github.com/NillerMedDild/Enigmatica6/issues/2354
~~Similar issue reported to Yung's Stronghold here: https://github.com/yungnickyoung/YUNGs-Better-Strongholds/issues/9#issuecomment-833182863~~
~~I think the comment the above link goes to has some good information as to what's going on here.~~

In singleplayer the internal server starts to lag when exploring the world, which results in an endless "waiting for server". World interactions are no longer possible and the world stops generating. The client side continues to work without problems.

~~Spark profile from Yung's Better Stronghold issue: https://spark.lucko.me/0a9pMaPI5k~~
Latest.log from original issue: [latest.log](https://github.com/NillerMedDild/Enigmatica6/files/6602236/latest.log)
Debug.log from original issue: [debug.log](https://github.com/NillerMedDild/Enigmatica6/files/6603145/debug.log)

**Comment by Won-Ton** [comment]
The profiler data shows a moment where you've used an eye of ender that triggered a structure search, and that search is asking YBS's stronghold for the position of where its structure starts. Basically all of the waiting time is attributable to YBS - presumably the way they generate their structure layout is quite expensive.

I'm not seeing anything about the server hanging indefinitely. The wait time on the structure search is saying 40ms (that's certainly enough to cause lag spikes but not hang the server).

----

I would say however that vanilla strongholds have special semi-hardcoded positions which are generated when you first create a world. The chunk generator holds a list of every location they'll generate at so it can find the nearest one really quickly without having to calculate the layout or anything.

YBS's strongholds look not to use these pre-determined positions and instead computes the layout each time you ask for its start point. If it takes upwards of 40ms each time then that could well slow down searching and cause lag spikes. Non-stronghold structures that generate this way (which is basically all of the other structure types) are typically designed to be very fast to compute their layout (they're also typically much smaller which helps)

**Comment by NillerMedDild** [comment]
Hmm I probably shouldn't mentioned the similar issue, it doesn't seem so similar now ^^' 
My issue, the one with latest and debug logs, does cause the server to hang indefinitely, although it's not clear in the logs. I cannot make a spark profile of it, as the server doesn't respond to anything. 

In this [comment](https://github.com/yungnickyoung/YUNGs-Better-Strongholds/issues/9#issuecomment-833182863) the dev of YBS has an idea of where generation is getting stuck. Don't know if you read that already, or if that's helpful ^^' 

Is there anything I can provide to make this issue debuggable?

**Comment by Won-Ton** [comment]
There's nothing in the logs that suggest your hang is anything to do with TF. I don't know what provides the "waiting for server" message as that's not a vanilla thing that I'm aware of.

Server hangs are usually caused by structures requesting chunks whilst generating - these types of hang are usually caught and reported by TF's 'server hang' detector if you have that still enabled.

The comment you're referring to from YBS is saying the same thing as me. Not sure why they've pointed you this way. I can only confirm that TF doesn't do anything to slow down the bit of code they're using that they're saying is slow. It may be that this performance issue of theirs is unrelated to the hangs - could be a different structure entirely.

As for profilers; consider using a tool external of minecraft like visualvm. These are external applications that you run and then select the minecraft java process to tap into. From there it has tools similar to spark where you can see thread and memory usage and whatnot but you can 'attach' even after the server/client process has hung.

**Comment by NillerMedDild** [comment]
> I don't know what provides the "waiting for server" message as that's not a vanilla thing that I'm aware of.

It's from The One Probe, it shows on it's HUD when the server is lagging. 

I'll try my luck with VisualVM, thank you :)

**Comment by NillerMedDild** [comment]
Just fyi, I managed to get a VisualVM snapshot of the game while in the deadlocked state:
[snapshot.zip](https://github.com/TerraForged/tracker/files/6604893/snapshot.zip)

I can't make much sense of it tbh, other than it's waiting for a chunk, but I don't see anything pointing towards TF.

**Comment by Won-Ton** [comment]
Maybe try resetting your TF performance config. Just noticed it isn't on defaults and if anything's going to break TF it's having the wrong set of values there ('wrong' can be different from machine to machine).

**Comment by NillerMedDild** [comment]
Oh, alright, I'll try that.
I noticed that the config values are generated based on the machine they're on - Shouldn't hardware dependant settings such as that not be configs? Since the packdev will make the config and then redistribute it to everyone else, no matter their hardware.

**Comment by Won-Ton** [comment]
It's only the core count parameter that's based on the machine, and that's not the setting that's going to break things (unless the pack creator is running an unsupported cpu with like <= 2 cores or something).

The other default settings are the ones that we test and 'certify' for general use and should work fine with any core count value > 1.

You're right in that this probably isn't a config file a pack creator should really be redistributing. I can add a comment to that effect in the file header but it is absolutely valid to have it as a config though.

**Comment by NillerMedDild** [comment]
Fair enough, thanks for the explaination ^^ A comment about it in the config would be nice, I'll make sure not to distribute it going forward.

**Comment by NillerMedDild** [comment]
The issue persists with freshly generated configs, sadly.

**Comment by yungnickyoung** [comment]
> The comment you're referring to from YBS is saying the same thing as me pretty much. Not sure why they've pointed you this way.

Well, because this has never been reported on a non-Terraforged world. That alone tells me it has to be a compat issue, with TF or something else perhaps.

**Comment by Won-Ton** [comment]
Yeah I can appreciate that. It's just that from the provided information you can see all the waiting time is happening within your code so that'd be the first place to look. _Then_ if your findings demonstratably point at TF that information can be shared here.
It reduces the amount of ping pong for the user :)
