### ISSUE TITLE
[ Issue ] java.lang.NullPointerException & First time loading problem

### ISSUE THREAD

**Issue by zndrmn** [TerraForged/tracker#161]
**Issue-1**
java.lang.NullPointerException / Description: generating biome surfaces (TerraForged World-Gen)
**Issue-2** 
First time loading problem / Client joins but screen gets stuck on the loading UI, after crashing the game you're able to join correctly. 

TerraForged Version = 0.2.16-BETA-2
Minecraft Version = 1.16.5
OptiFine Version = G8
Forge Version = 36.2.8

Configs :
[preset](https://gist.github.com/zndrmn/3fd61010e90536e556b3536dba98c263)

Logs :
[Latest.log](https://gist.github.com/zndrmn/6be596fe6edbaf186540ecb68534ef75)
[crash.txt](https://gist.github.com/zndrmn/27756c7fb01f8dca73afd8c4c46d5006l)

Note :
Whenever I try to create a terraforged world I have to crash the game once it's done generating the world, I check this by looking at the lastest.log file. I says that my client has joined the world but the screen will always be stuck on "loading world" *_I use console experience so the loading screen is different_

**Issue-1 and Issue-2 are very inconsistent after further testing**
Honestly this could be a fluke or something rare but I still want to report theses issues because someone's world could get corrupted potentially from these issues.

**Comment by Won-Ton** [comment]
You will need to report this to the creator of the mod pack so that they can investigate which mod is the issue. It’s unlikely to be TF. 

By the sounds of it the chunk generation completed and another mod has errored preventing you from joining.

The crash report you linked doesn’t exist and the log is incomplete or doesn’t show anything useful. You’ll want to try fix that when you report to the mod pack creator to help them out
