### ISSUE TITLE
[REQUEST] Disable Ore Gen from Terraforged

### ISSUE THREAD

**Issue by SaveTheJohnDoe** [TerraForged/tracker#166]
Terraforged implements its own vanilla oregen - https://github.com/TerraForged/TerraForged/blob/dcbefa931c5e9b16e6fbc6b333f3dd1bce27dc3c/src/main/java/com/terraforged/mod/data/gen/feature/Ores.java

Is there a way to disable this to avoid conflict with oretweaker when implementing ores at a modpack level? See https://github.com/EwyBoy/OreTweaker/issues/39 for terraforged influence on oretweaker, it overrides the vein size, spawn rate and max Y levels for vanilla ores.

**Comment by Won-Ton** [comment]
disable "custom features" in TF's misc settings

**Comment by SaveTheJohnDoe** [comment]
Ah cheers! Will the custom features disable other stuff as well? Can't seem to find more info on the documentation apart from the tooltip which mentions the trees. Not too bothered with those as I got dynamic trees to handle those.

**Comment by DigitalWendigo** [comment]
Another alternative to avoid having to disable custom features, is to dive into the .jar file itself and delete the ore generation of Terraforge. Doing so avoids any potential conflicts with mods mthat alter ore generation. 
This does however mean that you can't use the mod in a public modpack because curseforge will download the original file instead of the one you modified.

**Comment by Won-Ton** [comment]
>  ...is to dive into the .jar file itself and delete the ore generation...

Or just include a datapack with your modpack that overrides those files and sets the biome to something like `minecraft::void` so that it doesn't apply to any other biomes.

```json
{
  "biomes": ["minecraft:void"],
  "match": [],
  "transform": {}
}
```
