### ISSUE TITLE
getting EXCEPTION_ACCESS_VIOLATION during server worldgen

### ISSUE THREAD

**Issue by HarroldSaxon** [TerraForged/tracker#175]
I keep having the java environment, not minecraft, crash during world gen. removing any single mod from my list doesn't solve the issue with the exception of terraforged itself. disabling terraforged world gen also solves the crash.
[hs_err_pid3560.log](https://github.com/TerraForged/tracker/files/7860032/hs_err_pid3560.log)
[2022-01-12-1.log](https://github.com/TerraForged/tracker/files/7860036/2022-01-12-1.log)
[debug-1.log](https://github.com/TerraForged/tracker/files/7860037/debug-1.log)

**Comment by Won-Ton** [comment]
This crash isn't caused by TerraForged.

Looks like one of your others mods is doing something very dodgy within world-gen code which is why TerraForged is mentioned.

The logs suggests the culprit is "osv" which I believe is OreStoneVariants. A quick search of their issue tracker and it seems someone had a similar crash with vanilla world-gen which was apparently fixed a few days ago:
<https://github.com/PersonTheCat/OreStoneVariants/issues/142>

I'd suggest you try the updated version of it or just remove it.
