### ISSUE TITLE
incompatibility with RoadRunner and Starlight

### ISSUE THREAD

**Issue by Subthy** [TerraForged/tracker#180]
Hello,

So there's an issue, you're mod is not compatible with RoadRunner and Starlight, well it works together, but servers keep deadlock a lot and most of the time there is no crash report, but I am adding some that might help.

Best of luck,
- Sub

[crash-reports_crash-2022-02-27_05.46.30-server.txt](https://github.com/TerraForged/tracker/files/8213523/crash-reports_crash-2022-02-27_05.46.30-server.txt)
[crash-2022-02-28_19.20.34-server.txt](https://github.com/TerraForged/tracker/files/8213524/crash-2022-02-28_19.20.34-server.txt)

**Comment by Won-Ton** [comment]
Hi.

There's nothing in those reports to suggest TerraForged is the cause of either deadlock.

1. [crash-reports_crash-2022-02-27_05.46.30-server.txt](https://github.com/TerraForged/tracker/files/8213523/crash-reports_crash-2022-02-27_05.46.30-server.txt)
In the first report it doesn't even appear that TerraForged is the active chunk-generator.
The deadlock is passing through this:
```
strikerrocker.vt.enchantments.HomingEnchantment.onArrowJoinWorld
```
You should probably start by looking at whatever mod that^ belongs to and any mods that might interfere with it.

2. [crash-2022-02-28_19.20.34-server.txt](https://github.com/TerraForged/tracker/files/8213524/crash-2022-02-28_19.20.34-server.txt)
In the second report the deadlock is occuring whilst the game is trying to save a chunk. TerraForged has nothing to do with this so again is not mentioned anywhere that suggests it is the cause. You do however have a lot of mods installed that look like they modify how chunks are saved which are more likely to be the issue.

You should report this to the creator of the modpack or, if that's you, do some investigatation to find which mod or combination of mods are the cause.

**Comment by Subthy** [comment]
Well the thing is. I am running 2 servers, both are identical only one has TerraForge and the other one doesn't. The one with TerraForge is being deadlocked only. I removed Starlight and Roadrunner and it stopped deadlocking.

**Comment by Won-Ton** [comment]
Unfortunately that doesn't point to anything conclusive. 

Getting the game into a deadlocked state can come down to many different factors. Even with identical modlists, if one of those mods can cause deadlocks you could see a massive variance in the time it takes one server to crash vs another.

It may also be true that a deadlock bug in 'mod A' is triggered more frequently due to the presence of 'mod B', but the fault is still wholly on 'mod A' for containing such a bug. The fact that an unrelated mod could affect it that way points to further concerning issues with that mod honestly.

**Comment by Won-Ton** [comment]
Feel free to open a new ticket if you find anything more concrete that points to TF. I'll be happy to take a second look
