### ISSUE TITLE
TerraForged Crashes When Generating Structure From Other Mods

### ISSUE THREAD

**Issue by GrandAlbert** [TerraForged/tracker#181]
my terraforged world keeps on crashing due to world generation from other mods
It always says something along the lines of "com.terraforged.mod.profiler.watchdog.UncheckedException: Critical error detected whilst generating Feature"
This happened 4 times already but with different structures from different mods such as Create & Extractures & Yung's better dungeons
Here's an example of a crash report

https://pastebin.com/bVtwG4eU

and also:

https://pastebin.com/Zua6dWPG

**Comment by gavindegreen** [comment]
There are very apparent issues when it comes to structure generation compatibility with so many mods. There are so many structures generated that just look completely out of place. However, I don't believe that I have personally experienced any crashes related to the mod.

**Comment by GrandAlbert** [comment]
That's great to hear, but do you mind helping me find the cause of this problem because it seems to be terraforge everytime according to the crash reports. So this way I know what to do when fixing the issue

**Comment by Won-Ton** [comment]
Hi. These crashes are due to the distant horizons mod. It looks like they're generating extra chunks 'behind the scenes' but are doing it seemingly in an unsafe way that breaks structure mods like the ones you mentioned.

I'm guessing they add in safety measures to the vanilla chunk generator to prevent crashes there, but don't have the same for modded chunk generators. Nothing I can do about that sorry.

**Comment by GrandAlbert** [comment]
Yep Ive fixed it now it was due to distant horizons, thanks guys!
