### ISSUE TITLE
Crash with Better Mineshafts

### ISSUE THREAD

**Issue by skel39eek66** [TerraForged/tracker#184]
Hi there!
Minecraft is instantly crashes due TerraForged trying to generate a mineshaft from **YUNG's Better Mineshafts** (but it fails, of course).

Crash Report: https://pastebin.com/3xrypXpx

Latest Log file: https://gist.githubusercontent.com/Fleyzi/a3f0f5a441e8053546d64e1a0566307a/raw/892e2eea1d2baf9016e9f82dcc812de823510bae/latest.log

Debug log: https://gist.githubusercontent.com/Fleyzi/219e95b8b3bd1866ea217e940e27f389/raw/d553dee7f4aadfe3fba963ced0cf67bd4b7bb7d3/debug.log

**Comment by Won-Ton** [comment]
Hi. The crash is coming from the better mineshafts mod. 

This might be due to any of the following:
1. A bug in the YBM mod
2. Another mod changing something that breaks YBM
3. The fact that you're generating chunks at `x=-134,217,728, z=-134,217,728`. Minecraft's "safe" gameplay area is from +-30,000,000 blocks so exploring outside of those bounds may cause weird behaviour (crashes). If your player charactor is actually within that safe region then it may be that one of your mods is requesting chunks at these extreme distances.
