### ISSUE TITLE
Terraforged causing lag spikes

### ISSUE THREAD

**Issue by ghost** [TerraForged/tracker#187]
Played via ShadowPC remote computer https://shadow.tech/ (although I don't think this is the cause)
Mods: Spark 1.9.1 + Terraforged 0.2.16-BETA-2
Forge: 36.2.34
Difficulty: Peaceful
Generate Structures: Off

In the videos below you can see that Terraforged is randomly causing intermittent lag/tick spikes:

Video of flying around **without** Terraforged: https://streamable.com/z163yv
Video of flying around **with** Terraforged: https://streamable.com/pj2ej2

Spark profiler with Terraforged: https://spark.lucko.me/kXvrvqMT6j 
Spark profiler without Terraforged: https://spark.lucko.me/Njh954jq7b

For some reason, the Spark profiler doesn't show a big difference between the two, even though you can clearly see the lag spikes in the video.

**Comment by Won-Ton** [comment]
Hi. TerraForged world-gen (on 1.16.5) is generally a bit a slower than vanilla due to it doing a lot more work to make the terrain look (what we consider) nice. As such some CPUs can struggle a bit when you're generating lots of chunks, and quickly at that (in normal game-play you're not likely to be generating chunks as quickly as is possible when flying around in spectator mode).

I couldn't find much in the way of specs on your service's website but their 'power' option only offers a 2.8GHz base-clock CPU. It says it can boost to 3.6GHz but I'd imagine that would depend on the amount of demand/usage being shared across each user. Minecraft is a game that really benefits from consistently high clock-speeds.

As you mentioned, the profiling data doesn't really point to any one thing in particular (I'm not seeing anything that is taking an exceptionally long time) which suggests to me the CPU is just struggling to crunch through its tasks fast enough to meet minecraft's tick rate.

Suggestions: you could lower your view distance, use a preset that dials back some of the settings, or pregenerate a big piece of the world upfront so that you reduce the number of chunks that need to be generated whilst playing
