### ISSUE TITLE
Volcanoes not using BoP volcano biome

### ISSUE THREAD

**Issue by BloopsThePurple** [TerraForged/tracker#25]
Even with volcano biome usage cranked up to 1.000, the two BoP volcanic biomes are not used. I did a data dump and nothing is registered for the volcano terrain. If I had to guess, it's probably because the volcanic biomes are island biomes and there is no island terrain. Hence why tropics also don't generate.

**Comment by Won-Ton** [comment]
It's because they categorise their biome as 'none' so TF ignores it.
https://github.com/Glitchfiend/BiomesOPlenty/blob/BOP-1.16.4-13.x.x/src/main/java/biomesoplenty/common/biome/overworld/VolcanoBiome.java#L35

**Comment by drakray** [comment]
I came for that because I found it weird too that I couldn't find any BoP.Volcano

Since BoP for 1.16.5 is not in active development anymore, could it be possible for Terraforged to do something like 
```
If (feature.Volcano){
  if(BoP.Biomes.Volcano is available){
    use BoP.Biomes.Volcano as biome in feature
  }
}
```

I think that would "fix" it, and allow to have/use a real Volcano biome, for which I think only BoP's have one
And if it can use the BoP's biome material/decoration, that would be perfect, I think.

If you cant/don't want to it's ok too, just an idea like that :D

Thank you for your good work :)
