### ISSUE TITLE
Modded structures not properly generating(mod v.0.2.3)//not generating at all(mod v.0.2.4)

### ISSUE THREAD

**Issue by Kayatwo** [TerraForged/tracker#38]
Forge ver. 35.1.37
Minecraft 1.16.4

**Mod v.0.2.3**
Structures from "The Conjurer" and "End Remastered" and a couple of others are not being found via /locate in a TF world. End Remastered uses eyes of ender to find one of the structures, just like finding a vanilla stronghold. This does not work in a TF world. The structures are however being generated, which leads me to believe that they aren't being recognized as structures by the game, but as part of the terrain and therefore being ignored.
In a non TF world the structures are being properly located.

**Mod v.0.2.4**
The modded structures from the above named mods aren't generating at all.

Everything  was tested in a separate instance with only TF and said mods being installed.
I hope this information helps in resolving the issue.

**Comment by Won-Ton** [comment]
In both cases it's because they haven't registered their structure settings and instead try to inject them directly into the chunk generator which doesn't work with TF.

You might be able to make a datapack that includes both mods' structure settings so that they're correctly registered and visible to TF to use. The file to override in the datapack would be:
```
/data/minecraft/worldgen/noise_settings/overworld.json
```

You should be able to find this file in the zip linked here (slicedlime works at mojang):
https://github.com/slicedlime/examples/
