### ISSUE TITLE
End Remastered Structures not Locating When Using Terraforged

### ISSUE THREAD

**Issue by maxmitchelson** [TerraForged/tracker#60]
Hello! I am one of the developer of End Remastered and this issue is in reference to issue #38. 

I noticed that multiple users of our mod report problems with locating our custom structures when they use it with TerraForged. You seemed to indicate in issue #39 that the problem could be fixed easily with a five line change, but, unfortunately, I could not figure out what was the exact source of the issue and was hoping you could help us out by pointing out what was the exact problem.

**Comment by Won-Ton** [comment]
Hi there! We recently added a section on our wiki about this, it has a code snippet at the end:
https://github.com/TerraForged/TerraForged/wiki/Mod:-Structures:-Compatibility

Basically the settings need to be present in the data used to intialize the ChunkGenerator rather than being added later. The linked code is the conventional way of achieving that
