### ISSUE TITLE
[Issue] Desolation (Forge) Charred Forest biome not generating in Terraforged world type.

### ISSUE THREAD

**Issue by Corvus20** [TerraForged/tracker#72]
I had brought up adding the correct tags and stuff to the mod/port's dev, and they implemented such things to the biome, but apparently something is not working. When I mentioned this is wasn't working the dev responded with this:

"you should open a issue on the github of their page since i added the Type.Forest to it (this is an overworld biome type) if this is not working for you then the devs should change the way how terraforge detects overworld biomes."

Being that when similar issues are not common with other mods, I would more likely assume they are doing something wrong. I am just asking for insight into what needs to be fixed in order for the mod's biome to generate, so I can relay that info to the dev.

**Comment by Won-Ton** [comment]
There is literally a `Type.OVERWORLD` marker than mods can add to their biomes.

Forests can  exist in any number of non-overworld dimensions so just adding `Type.FOREST` is not sufficient for TF know if the biome is suitable for use.

They're closed source so I can't reasonably check their code for any other pointers.

**Comment by Y3Z0N** [comment]
your code should check in general for biomes that are generated in the overworld. there's literally a code for that in MCP you could use and override. forcing other devs to add lines of code is not a gut decision.

other mods does the same. why should other devs made their biome/dim mods compatible to terraforged and terraformed makes it not compatible to other mods.

I'll add this to my biome but its not okay from you / your team.

best reg, y3z.

**Comment by Won-Ton** [comment]
Hi. 

There is no other metadata that can be used to distinguish an overworld biome from one that's intended specifically _not_ to appear in overworld. The nether and end dimensions have their respective `Biome.Category`'s, but mods add many different types of dimensions not covered by those 2 categories. Forge added the `Type.OVERWORLD` specifically for this purpose.

Example: a mod might add some crazy fantastical dimensions with special magical forest biomes that should only appear in that dimension. If TF were to ignore `Type.OVERWORLD` tag and use their biomes in the overworld regardless (because they happen to be forests too) then we break the progression design for that mod - players no longer have to craft the doohicky to get to their dimension to harvest the unique stuff from the biome.

-----

TF is just working to a very common and widley adopted standard set out by Forge. This API  is there to the aid mods that want to work nicely with each other, and to do so more easily.

You're not obliged to work to those standards if you think they're 'not okay' on the grounds of you having to write code? or whatever. We'll stick to ensuring compatibility with mods that do make those basic efforts.
