### ISSUE TITLE
Repurposed structures and dungeons plus doesn't generate with terraforged world type (default gen profile).

### ISSUE THREAD

**Issue by JustReg2Download** [TerraForged/tracker#73]
Repurposed structures and dungeons plus doesn't generate with terraforged.

![image](https://user-images.githubusercontent.com/72761693/110027213-602bf200-7d3a-11eb-9305-e71b0761cfa3.png)

![image](https://user-images.githubusercontent.com/72761693/110026912-fad80100-7d39-11eb-999e-a3f3b77d89f4.png)
Forge version 1.16.5
Both of mods (terraforge also) are on 1.16.4
Is it a bug or my stupid fail?
For some reason I still can find vanilla stronghold.
![image](https://user-images.githubusercontent.com/72761693/110027457-ad0fc880-7d3a-11eb-8db9-078c8485c4bf.png)

Thanks for a great mod also, probably best of all gen mods <3

**Comment by JustReg2Download** [comment]
![image](https://user-images.githubusercontent.com/72761693/110027252-69b55a00-7d3a-11eb-9b09-5a511c74ff70.png)

**Comment by JustReg2Download** [comment]
![image](https://user-images.githubusercontent.com/72761693/110027285-7174fe80-7d3a-11eb-80c3-638d86fec1fb.png)

**Comment by JustReg2Download** [comment]
![Uploading image.png…]()

**Comment by JustReg2Download** [comment]
![Uploading image.png…]()

**Comment by JustReg2Download** [comment]
![image](https://user-images.githubusercontent.com/72761693/110027575-d3356880-7d3a-11eb-8f9d-e999a9991c9e.png)

**Comment by JustReg2Download** [comment]
![Uploading image.png…]()

**Comment by JustReg2Download** [comment]
![image](https://user-images.githubusercontent.com/72761693/110027942-4ccd5680-7d3b-11eb-8eaf-46f606558e5f.png)

**Comment by Won-Ton** [comment]
I think Repurposed Structures pushed out an update already with a fix for their structures.

----

I don't know about Dungeons Plus - if their structures show up in TerraForged's 'Structure Settings' screen in our UI then they should generate just fine. If they don't show up in that screen then they probably haven't registered their structure settings in the usual way.

You could refer them to this wiki page we made in hopes that they add the registration steps (it has a code example showing how to do it):
https://github.com/TerraForged/TerraForged/wiki/Mod:-Structures:-Compatibility

Otherwise you could make a datapack that adds all the structures you want by following this guide:
https://github.com/TerraForged/TerraForged/wiki/User:-Datapacks:-Structures
