### ISSUE TITLE
Buried Treasure did not generate

### ISSUE THREAD

**Issue by last903347** [TerraForged/tracker#76]
https://cdn.discordapp.com/attachments/687310841472876577/817831156154236948/2021-03-07_02.23.57.png
as the title when I use this mod in my mod pack, it seems that no Buried Treasure generated in this world. 
as the picture shown above when I tried to use locate command to get coordinates of a Buried Treasure, it finally gives me one but as in the picture nothing was in that coordinate. idk that's why there are no treasure maps in the ruins and shipwrecks.
by the way, I have both **_byg_** and **_biomes o' planty_** in the pack too. I'm not sure if this problem was caused by them.

**Comment by Won-Ton** [comment]
Hi. Have you tested with just TF installed because it 100% does generate the treasure chests _and_ the treasure maps in shipwrecks

I've been rigorously testing exactly that in the last week or so, so it's fresh in memory. It can be hard to locate using commands sometimes - I've had most success by searching for a shipwreck _then_ searching for treasure from that location - if there's a chest nearby there's usually a map in the shipwreck you're at (if not then there's usually another shipwreck nearby).

idk if other mods or datapacks you have installed might be interfering. TF can't do anything about that if so
