### ISSUE TITLE
Enhanced Mushrooms compat?

### ISSUE THREAD

**Issue by MilkMan1776** [TerraForged/tracker#83]
The biome decoration feature breaks enhanced mushrooms in "vanilla" biomes.
It's really a shame we can't have both, the custom mushrooms simply do not generate outside of modded biomes.

**Comment by Won-Ton** [comment]
Well the issue is that both mods replace the same vanilla feature so _both_ are at fault, not just TerraForged. We allow you to override this via datapack or outright disable our custom features as compatibility measures. I don't know what compatibility measures (if any) EM provide.

For the datapack route, you'd need to override the file at `data/terraforged/features/trees/dark_oak.json` in the TF mod jar. You'd edit the json to include the feature configuration for EM's mushrooms (you'd have to ask them what that json should look like).

Hope that helps
